name: getout_flutter_app
description: "GetOut Flutter App - Social event management application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP requests
  http: ^1.1.2
  
  # Local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Date/Time handling
  intl: ^0.19.0
  
  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  
  # Database
  cloud_firestore: ^4.13.6
  
  # Utilities
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
